- CMakeLists.txt
Been using cantata's CMakeLists to learn more on CMake and caught this little typo sneaking in.
> Tiny typo in CMakeLists.txt

- CMakeLists.txt
- online/podcastwidget.cpp
Qt 5.7 requires C++11 support from the compiler, thus set it if Qt version is greater than 5.6.99. Also, I've had a crash on startup due to a virtual function call from constructor on a partially initialized object. Worked around it by re-arranging constructor code.
> Fix compilation and a crash with Qt 5.7

- context/albumview.cpp
This change makes the list of tracks in the album view look a little bit cleaner by right aligning the track numbers.
> Right align track numbers in album view

- gui/mainwindow.cpp
- gui/mainwindow.h
This adds an new menu entry "Play Next" to the context menu of the playlist. "Play next" allows to move a selection of songs from the playlist directly under the currently played song.
> Play next action added (#952)

- gui/mainwindow.cpp
When compiling with KDE support enabled `iconCol` is not defined leading to a compiler error. This patch moves the declaration and initialization of that variable to outside of the `#define` block which resolves the error.
> Fix `iconCol` not defined with KDE support enabled

- po/ja.po
From #972. This fixes the following error:
```
po/ja.po:2822: message catalog has plural form translations...
po/ja.po:7: ...but header entry lacks a "plural=EXPRESSION" attribute
Try using the following, valid for Japanese:
"Plural-Forms: nplurals=1; plural=0;\n"
po/ja.po:7: ...but header entry lacks a "nplurals=INTEGER" attribute
Try using the following, valid for Japanese:
"Plural-Forms: nplurals=1; plural=0;\n"
```
I can't vouch for the accuracy of the translations, but it builds successfully now.
```
> Fix #972: Fix Japanese translations

- README
- gui/application.cpp
This fixes this compile issue on OS X:
```
/Users/mwheeler/Downloads/cantata/gui/application.cpp:46:17: error: no viable conversion from 'ProxyStyle' to 'ProxyStyle *'
ProxyStyle *proxy=ProxyStyle(ProxyStyle::VF_Side|ProxyStyle::VF_Top);
^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/cantata.dir/gui/application.cpp.o] Error 1
make[1]: *** [CMakeFiles/cantata.dir/all] Error 2
make: *** [all] Error 2
```
I've also updated the README to reflect installing qt5 from homebrew.
> Fix for latest qt5 avaliable from homebrew on OS X

- support/inputdialog.h
source/cantata/gui/mainwindow.cpp: In member function ‘void MainWindow::addWithPriority()’:
source/cantata/gui/mainwindow.cpp:1915:27: error: invalid use of incomplete type ‘class QSpinBox’
prio=dlg.spinBox()->value();
^
In file included from /home/tux/source/cantata/gui/mainwindow.cpp:31:0:
source/cantata/support/inputdialog.h:31:7: note: forward declaration of ‘class QSpinBox’
class QSpinBox;
> Fix build error

- cantata.desktop.cmake
The original translation omits the "current" part, making the function a bit confusing. This makes it clear in German that it's stopping after the current (aktuellem) track.
> Improve german translation for stop after current track

- CMakeLists.txt
- ChangeLog
- INSTALL
- README
- cmake/FindAvahi.cmake
- config.h.cmake
- gui/avahidiscovery.cpp
- gui/avahidiscovery.h
- gui/avahipoll.cpp
- gui/avahipoll.h
- gui/findmpddialog.cpp
- gui/findmpddialog.h
- gui/findmpddialog.ui
- gui/initialsettingswizard.cpp
- gui/initialsettingswizard.h
- gui/serversettings.cpp
- gui/serversettings.h
This commit adds automatic avahi service discovery to Cantata. A new
dialog is added to the initial settings wizard and the settings menu
which lets the user choose the correct host configuration for all MPDs
on the network automatically.
To compile this feature the following libraries have to be installed:
*libavahi-common
*libavahi-client
These are included in the following Ubuntu packages:
*libavahi-common-dev
*libavahi-client-dev
Any remaks and suggestions are welcome.
> Add avahi support (Issue #955)

- gui/serversettings.cpp
- gui/serversettings.ui
- gui/settings.cpp
- http/httpserver.cpp
- http/httpserver.h
- mpd-interface/mpdconnection.h
This allows to configure the local files streaming option per-connection. It defaults to enabled for existing and disabled for new connections.
[Debian does not like that this feature opens an HTTP socket](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=872704) and would prefer to have this configurable and disabled-by-default. Currently, cantata is built without support for streaming files to MPD on Debian, which I find unfortunate.
This is my first large PR against Cantata. I’m happy to make changes if I did anything not according to your liking.
> http: make HTTP server support configurable

- context/songview.cpp
- devices/actiondialog.cpp
- gui/librarypage.cpp
- mpd-interface/mpdconnection.cpp
- mpd-interface/mpdconnection.h
- mpd-interface/song.cpp
- mpd-interface/song.h
- replaygain/rgdialog.cpp
- tags/tageditor.cpp
- tags/trackorganiser.cpp
- widgets/playqueueview.cpp
- widgets/songdialog.cpp
forked-daapd(8) sends absolute path names with a prefix of `file:`. E.g.: `file:/srv/music/Vivaldi/xx.mp3`.
This is handled by the first patch.
After fixing this, I found that downloading covers now worked, but other things -- like editing tag information and the file link on the information page -- did not. This is handled by the second patch.
Some PlayQueue actions use a test for nonMPD files by looking for ":/", which obviously fails for forked-daap. This is fixed by the third patch.
> Forked daapd file prefix

- gui/serversettings.cpp
- gui/serversettings.ui
- gui/settings.cpp
- mpd-interface/mpdconnection.cpp
- mpd-interface/mpdconnection.h
- tags/tageditor.cpp
- tags/trackorganiser.cpp
- translations/cantata_de.ts
- translations/update.sh
After editing metadata, cantata sends an `update` command to the MPD server.
However, this triggers a rescan, which takes about 140 seconds for my forked-daapd(8) server.
The standard mpd(8) server is quite a bit faster.
I found that both forked-daapd(8) and mpd(8) detect added/changed/removed/moved files automatically and report changes via the `idle` event  `database`. The `update` command is therefore not necessary which results in a significantly increased response time for edits.
The option "Auto update" does just that. It suppresses the `update` command after an edit.
> Option to suppress update command after manipulating files

- models/playqueuemodel.cpp
- mpd-interface/mpdconnection.cpp
- mpd-interface/mpdconnection.h
- tags/trackorganiser.cpp
So this is the first draft of a server detection proposal. I have put everything in two places for easier review.
The response to`lsinfo` with a specific invalid URI provides the information to reliably detect MPD and forked-daapd. The invalid URI is designed to provide a user agent identification.
I think hiding this stuff in in its own class is better than expanding getStats(), but it must be integrated into MPDConnection in order to use sendCommand() which is private.
The rating problem is also addressed by sending a message to the rating channel. This is the solution I will propose to the forked-daapd team.
Let me know what you think and I will tweak this to your wishes.
> Proposal for MPD server detection

- gui/interfacesettings.ui
The checkboxes in Preferences->Interface->Toolbar were overlapping since
commit c30650adc.
> Fix overlapping checkboxes

- context/lastfmengine.cpp
The last.fm artist info comes with a "Read more on last.fm" link. This
link is removed in favor of our own link. Due to a change in the url of
the original link the removal did not work anymore so that the link was shown twice.
> Fix last.fm artist info presentation

- gui/initialsettingswizard.ui
- gui/mainwindow.cpp
- mpd-interface/song.cpp
- translations/blank.ts
- translations/cantata_cs.ts
- translations/cantata_de.ts
- translations/cantata_en_GB.ts
- translations/cantata_es.ts
- translations/cantata_fr.ts
- translations/cantata_hu.ts
- translations/cantata_it.ts
- translations/cantata_ja.ts
- translations/cantata_ko.ts
- translations/cantata_pl.ts
- translations/cantata_ru.ts
- translations/cantata_zh_CN.ts
Debian's `lintian` QA tool has highlighted the following spelling errors in cantata. `lintian` uses a list of common misspellings rather than a spellchecker.
This sequence of patches changes both the source and also the translation files. I assume that will prevent fuzzing of the translations and that this is the best approach (i.e. translators won't be prompted to confirm that the translations are still correct due to the source text being changed); please let me know if you'd rather only change the .cpp files. 
- therfore → therefore
- quiting → quitting
- orignal → original
Additionally, `lintian` flagged:
-  "Entrys → Entries" as a potential misspelling but I am unable to see it in the source
- "priorty → priority", however this seems not to be user-visible (only in variable names); …
> Spelling fixes

- widgets/playqueueview.cpp
- widgets/playqueueview.h
In the table play queue the drop indicator is almost not visible when
tracks get moved by drag'n drop. In addition the drop indicator is
only shown in only one column and does not span the whole row. This
change does fix both issues.
> Improve drop indicator in table playqueue

- mpd-interface/song.cpp
I think this addition would be useful.
Reasons why this code is "less than ideal" I could think of:
- basic() is applied both to artist and title fields, while producer names are never(?) encountered in artist fields
- I have encountered only the "prod. " pattern in my music library. I made the other up just to cover all cases but they may be exceedingly rare (Although that most likely doesn't matter because the extra computational cost is insignificant)
> mpd-interface: basic(str) now strips producer names too

- mpd-interface/httpstream.cpp
QMediaPlayer related code was not ifdef'ed out when libvlc is used resulting in compilation errors.
Probably similar checks have to be done when using libvlc as well, but I have only gotten it to compile as it is.
Introduced by @theirix's commit 4699dee13.
> Add missing ifdef for libvlc support

- mpd-interface/httpstream.cpp
- mpd-interface/httpstream.h
QMediaPlayer needs to fill its internal buffer before it can play the
stream otherwise it can end up in a stalled state.
This commit also simplifies the logic for when the player needs to be
restarted and remove the need of an internal timer to poll the player
state.
Fixes choppy http playback.
Tested on Linux using an mpd server streaming an opus stream at 510~ kbp/s (through nginx via https).
> Wait QMediaPlayer buffering before entering playing state

- 3rdparty/solid-lite/CMakeLists.txt
If `BUILD_SHARED_LIBS` is part of standard system cmake args:
```
cantata: error while loading shared libraries: libsolidlite.so:
cannot open shared object file: No such file or directory
```
While I'm at it: Since solid was split out of kdelibs4 as a separate part of KDE Frameworks, is there any appetite to unbundle this lib again?
> Fix solid-lite static linking

- context/lyrics_providers.xml
This adds various fixes to the lyrics providers XML.
All fixes are taken from clementine-player/Clementine
I went through all changes in Clementine between 0ad40780ea25a9ccb42987f21f361963ec152d42 and c4d6424e96fe4b692e1c2bbf7c49e9f3fbf0e0e4
I skipped the genius.com patches as @aqua36 already submitted them to Cantata as well.
My main motivation was that the "nothing found" detection in the "lyrics.com" plugin was broken:
```
$ grep -R 'Click to search for the Lyrics on Lyrics.com' ~/.cache/cantata/lyrics/ | wc -l
113
```
> Lyrics provider fixes

- mpd-interface/mpd.conf.template
Instances of MPD started by Cantata do not need to register with Avahi, but zeroconf_enabled defaults to "yes" (https://github.com/MusicPlayerDaemon/MPD/blob/ce49d99c2f3265f2975b2cff583684bf191bbd93/src/zeroconf/ZeroconfGlue.cxx#L47)
> Disable zeroconf for local MPD instances

- README
I updated the procedure for commandline to be more explicit. Tested on my local machine and was able to create the dmg and install using the steps I wrote.
> Update Mac install process to include command line guide

- widgets/itemview.cpp
- Center the items even if there is only one column
> - Remove a bit of the extra spacing on the right of itemview

- 3rdparty/solid-lite/devicemanager.cpp
- ChangeLog
Directly deleting `DevicePrivate` members from within the destructor of `DeviceManagerPrivate` can lead to a crash in Qt's internal memory management. Better defer destruction by using `deleteLater()` like it has already been done in [DevicePrivate::setBackendObject()](https://github.com/CDrummond/cantata/blob/efa907c8e03d052718f14834eb968da86d1c34d8/3rdparty/solid-lite/device.cpp#L312).
> Prevent Cantata from potentially crashing when closing

- ChangeLog
- online/onlineservice.cpp
This seems to be a copy-paste error. Before the fix, 'time', 'year' and 'disc' have also been mapped to `song.track`. So it happened that the information about the duration of podcasts was missing for instance (and track number was set to garbage instead).
> Fix setting song details in OnlineService::decode()

- ChangeLog
- support/utils.cpp
Always handle the construction of the path in the same way no matter which OS Cantata is built for, and only then pass the complete path to `Utils::fixPath()`.
> Align path construction in Utils::systemDir() and Utils::helper()

- online/podcastservice.cpp
Check whether the string object `localFile` is nonempty to get rid of _"Empty filename passed to function"_ console messages while loading podcasts. I know that this issue has been fixed in Qt 5.12, but if you have an older Qt release, this message is flooding the console. It's just annoying.
> Avoid passing empty string as file name to QFile::exists()

- gui/covers.cpp
- gui/currentcover.cpp
- gui/currentcover.h
- widgets/coverwidget.cpp
The default icons shown as fallback in the play queue and the tray item should be the same as well if no cover has been found. So I changed `CurrentCover::stdImage()` to return `Icons::podcastIcon` if no image could be found as cover for the current podcast as well as I changed `Covers::defaultPix()` to return `Icons::streamIcon` if there is no separate image for something from the internet.
In addition, I changed the search order for icons in `CurrentCover::findIcon()` to stick with the same icon theme as long as possible, i.e., first check all storage locations with the same icon theme for the wanted icon before to switch to the next icon theme.
> Fix default cover icons

- gui/currentcover.cpp
Sorry for forgetting to update `coverFileName` in accordance with `Current::stdImage()` and, thus, the additional pull request.
> Correctly setting coverFileName which is missing in pull request #1590

- ChangeLog
- mpd-interface/mpdparseutils.cpp
The problem comes up when playing local audio files without tags (esp. missing title information). In this case the information returned from `HttpServer::decodeUrl()` would have been completely ignored, e.g., `Song::time` which is why the duration information is missing in the play queue.
> Fix getting song details from Cantata stream URLs

- ChangeLog
- dbus/mpris.cpp
- dbus/mpris.h
I have fixed and re-enabled `CanPlay`/`CanPause` as well as I have fixed `CanGoNext` (which is now false if it is already the last item playing) and `CanGoPrevious` (which is now false if it is the first item playing). In addition, both properties `CanGoNext` and `CanGoPrevious` are always updated when the play queue changes or the position of the currently selected item (which includes switching to the next song and similar things).
> Amend MPRIS interface

- ChangeLog
- dbus/mpris.cpp
- dbus/mpris.h
- gui/mainwindow.cpp
- mpd-interface/mpdconnection.cpp
- windows/thumbnailtoolbar.cpp
- windows/thumbnailtoolbar.h
As already partly discussed in #1592, this fixes enabling of the play queue navigation actions 'next' and 'previous'. I've tested it, it's properly working for me since 10 days and I hope I've covered almost all use cases. Craig, what do you think?
> Fix enabling of play queue navigation actions 'next' and 'previous'

- ChangeLog
- dbus/powermanagement.cpp
- dbus/powermanagement.h
1. Make the fallback to freedesktop.org's power management working by fixing its bus name.
2. Amend the implementation by
– additionally calling `Inhibit()` from `org.freedesktop.login1.Manager` to also support desktop environments that do not provide the interface `org.freedesktop.PowerManagement.Inhibit` (which is the case for newer GNOME releases for instance) and by
– using `QGuiApplication::applicationDisplayName()` instead of `QCoreApplication::applicationName()` for a consistent spelling of the application name (cf. `Notify::show()`).
> Fix and amend invocation of sleep inhibition

- ChangeLog
- support/utils.cpp
- Since 2017, Unity is yet a special Ubuntu flavor of GNOME. That is why system tray support with `QSystemTrayIcon` is only provided if the Ayatana Indicator application or the GNOME Shell extension AppIndicator or something similar that implements `org.kde.StatusNotifierWatcher` is installed and running. Hence, Unity should be treated the same as plain GNOME.
- Although Qt prefers to internally use `QDBusTrayIcon` for `QSystemTrayIcon` (cf. qt/qtbase@38abd653774aa0b3c5cdfd9a8b78619605230726), there is also a fallback implementation using XCB if Qt has X11 support and `org.kde.StatusNotifierWatcher` is not registered on D-Bus. There are settings with some desktop environments where none of these mechanisms are available. So it is not safe to assume `QSystemTrayIcon` is working if …
> Query Qt whether system tray is available if not (Unity flavored) GNOME

- ChangeLog
- online/podcastservice.cpp
- Fix writing 'descr' attribute in PodcastService::Podcast::save().
-  Insert additional line break between title and description in tooltip to better separate long titles from the descriptions.
> Fix writing 'descr' attribute when saving podcast information

- ChangeLog
- context/view.cpp
- widgets/textbrowser.cpp
* Fix loading images with wrong file extension in `TextBrowser::loadResource()`.
* Amend `View::createPicTag()` by using a `<div>` container instead of the `<table>` work-around to center the covers in the context view because the latter sometimes does not seem to work properly.
> Fix loading and showing cover images in context view

- ChangeLog
- mpd-interface/song.cpp
Avoid prepending song's file path with MPD's music directory if it is empty, a stream URL (by checking `isNonMPD()` or an absolute path (those from UNIX starts with a slash though, but on Windows it's something like `C:/...`).
> Fix Song::filePath()

- ChangeLog
- gui/mainwindow.cpp
MPD reports an error unless we ignore current song in selection when moving selected songs within the play queue to play them next.
> Fix MainWindow::moveSelectionAfterCurrentSong()

- translations/blank.ts
- translations/cantata_cs.ts
- translations/cantata_da.ts
- translations/cantata_de.ts
- translations/cantata_en_GB.ts
- translations/cantata_es.ts
- translations/cantata_fi.ts
- translations/cantata_fr.ts
- translations/cantata_hu.ts
- translations/cantata_it.ts
- translations/cantata_ja.ts
- translations/cantata_ko.ts
- translations/cantata_nl.ts
- translations/cantata_pl.ts
- translations/cantata_pt_BR.ts
- translations/cantata_ru.ts
- translations/cantata_zh_CN.ts
- translations/update.sh
- Tweak `translations/update.sh` to ignore generated source files found in build directory.
- Incorporate current source line offsets.
- Purge obsolete entries.
- Sort entries according to source line numbers.
- Add translations provided by 'same text' heuristic.
> Clean up translation files

- playlists/cantata-dynamic
This fixes #1627 on my machine. Dynamic Playlists that look like this now include unrated songs:
This does not handle Dynamic Playlists with rating rules but no include/exclude rules ([separate flow](https://github.com/CDrummond/cantata/blob/master/playlists/cantata-dynamic#L761), I'm not sure if unrated songs are [included here](https://github.com/CDrummond/cantata/blob/master/playlists/cantata-dynamic#L645))
My first time writing Perl, let me know if I wrote something "non-Perlonic" :sweat_smile:
> Fix #1627: Check for includeUnrated in Dynamic Playlists with rating and include rules

- translations/cantata_cs.ts
Multiple genres example in tag editor used semicolon instead of comma.
> Fix typo in Czech translation

- tags/filetyperesolver.cpp
- tags/filetyperesolver.h
The taglib True Audio loader seems to erroneously accept ogg-contained opus files. This results in ID3 tags being written to ogg opus files. This is especially apparent when using replaygain, as ID3 RVA2 and `replaygain_track_gain` tags are written instead of `R128_TRACK_GAIN`. 
Existing wrongly-tagged files can have their ID3 tags removed using something like `mutagen`, with
```python3
import mutagen.id3
mutagen.id3.ID3('/path/to/file.ogg').delete()
```
I have not tested this against TrueAudio files. It is possible that the opus loader will consider True Audio files valid.
> Fix ogg opus file type confusion in cantata-tags

- context/wikipediaengine.cpp
> Replace &mdash; in wikipedia description

- context/contextwidget.cpp
I am unsure why the picSize*2.5 calculation was used in the first place and maybe this is only an issue with my setup/dpi, however this patch fixed it for me. Someone else might need to verify.
before:
after:
> Fix Album, Artist and Song overlap on sidebar resize

- mac/dmg/create-dmg.sh.in
CMake's install procedure invalidates the signatures auto-generated by
the compiler, so without this MacOS will refuse to launch Cantata.
> Fix the code-signing on MacOS

- gui/mainwindow.cpp
Qt interprets '&' inside action text as a key shortcut, so we should
escape it.
> Fix formatting of collection/output/partition names containing '&'

- models/playqueuemodel.cpp
Hey, I wanted this feature for my personal use - feel free to close if you're not interested in upstreaming it :sweat_smile: 
I have a collection of low-quality metadata files like:
- SomeAlbum/1001_SongA.mp3 (Album: `SomeAlbum`, Title: `Song A`, Track Number: `1`)
- SomeAlbum/1002_SongB.mp3 (Album: `SomeAlbum`, Title: `Song B`, Track Number: `2`)
- SomeAlbum/2001_SongA.mp3 (Album: `SomeAlbum`, Title: `Song A`, Track Number: `1`)
- SomeAlbum/2002_SongB.mp3 (Album: `SomeAlbum`, Title: `Song B`, Track Number: `2`)
Ideally, these tracks would either be in separate albums (`SomeAlbum Part 1`, `SomeAlbum Part 2`) or have proper non-overlapping track numbers, but this is not the case. The easiest way to play them in order without modifying the source files is to sort them by filename. I've …
> Allow sorting a playqueue by filename/path

- 3rdparty/solid-lite/backends/udisks2/udisksblock.h
> Fixes a build error with musl libc.  Turns out this is the required
> header for dev_t, and not just for FreeBSD.  That it works without on
> glibc is just an accident.
> 
> Differential Revision: https://phabricator.kde.org/D6596
> 
> (cherry picked from commit 2382c3f8d3669c473130f4baefb68d244dcb5cbc)
Patch picked from upstream solid.
See also downstream report: https://bugs.gentoo.org/792555
Is there any appetite to support upstream KF5Solid in cantata?
> Fix build with musl libc - require sys/types.h for dev_t unconditionally

- gui/main.cpp
See also downstream report: https://bugs.gentoo.org/807763
Follow-up to https://github.com/CDrummond/cantata/pull/1729
Picked from VoidLinux:
https://github.com/void-linux/void-packages/commit/188bc4852af59e20f60b186e7acaaaa4b8ce51ab#diff-413d61b1a38989fbf79759fb57901b99d629706587f21aa4b1b19fb8ef23fd4b
> Fix gui/main.cpp build with musl

- tags/tageditor.ui
The artist and composer combo boxes can grow extremely wide for some tracks causing the tag editor window to span nearly the entire width of the screen.  Adding the AdjustToMinimumContentsLengthWithIcon property for these two combo boxes fixes the window from growing too wide but keeps the ability to view long artists and composers.
> Fix tag editor window width issue

- 3rdparty/qtsingleapplication/qtlocalpeer.cpp
Fixes build failures on MacOS.
On an M1 Macbook Air running Big Sur (11.6), builds against master are erroring with:
```
[  3%] Building CXX object 3rdparty/qtsingleapplication/CMakeFiles/qtsingleapplication.dir/qtlocalpeer.cpp.o
/Users/kevin/src/cantata/3rdparty/qtsingleapplication/qtlocalpeer.cpp:96:56: error: no member named 'getuid' in the global namespace
socketName += QLatin1Char('-') + QString::number(::getuid(), 16);
```
The issue appears to have been introduced in https://github.com/CDrummond/cantata/commit/c8aa02230e37a63fccb88b62f05f4c7d62b4e9a5, I'm guessing due to some nested `#include <unistd.h>` that happens on Linux but not MacOS.
> Fix missing references to getuid when building on MacOS

- .github/workflows/github-actions.yml
Following recent discussion on https://github.com/CDrummond/cantata/issues/1704#issuecomment-939251569 and https://github.com/Homebrew/homebrew-core/pull/86834 I thought I would share this github actions workflow. It certainly needs more testers and possibly a look from somebody more used to the github actions ecosystem than I am, but seems to work.
> Added a github actions workflow to build Cantata dmg for macOS

- models/playqueuemodel.cpp
Reordering the play queue by dragging and dropping often results in the total time at the bottom becoming incorrect (too short) due to moved songs having a `time` of 0.
Not sure if I'm missing something or this is specific to something about my setup, because I would have expected this to be noticed before. For me, it's consistently reproducible with at least Cantata 2.4.2 and master and the last few versions of MPD (currently on 0.23.2). Simplest reproduction: Add two songs to an an empty queue, drag the first one after the second one (or the second before the first) and watch the total time at the bottom change to reflect only the (now) second song in the list.
This change would be problematic if the song in the new list (which matches the id of an existing song) has the `time` field …
> Fix total time after reordering play queue

- ChangeLog
- widgets/coverwidget.cpp
The line break appears to have originally separated textual information
in the tooltip from the cover image. All the textual information was
removed in 2d8566d74332491d79d6ecbc71a5c2d73fc914ba, so the image is now
the only thing in the tooltip and the line break was just creating an
empty space above it.
> Remove superfluous line break from cover tooltip

- replaygain/ffmpeginput.cpp
ffmpeg 5.0 changes the API slightly that causes cantata to fail to build from source:
```
[ 96%] Building CXX object replaygain/CMakeFiles/cantata-replaygain.dir/ffmpeginput.cpp.o
.../replaygain/ffmpeginput.cpp: In constructor ‘FfmpegInput::FfmpegInput(const QString&)’:
.../replaygain/ffmpeginput.cpp:193:43: error: invalid conversion from ‘const AVCodec*’ to ‘AVCodec*’ [-fpermissive]
193 |         handle->codec=avcodec_find_decoder(handle->formatContext->streams[handle->audioStream]->codecpar->codec_id);
|                       ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|                                           |
|                                           const AVCodec*
.../replaygain/ffmpeginput.cpp:214:71: error: invalid conversion …
```
> Make compatible with ffmpeg 5.0
